spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.201.144:3306/vpn?useUnicode=true&characterEncoding=utf-8
    username: ENC(WXEhZxlFfSq19Wa1EEuBzQ==)
    password: ENC(Bjv021k+DHXfIom1AqrXeg/bXK94a3Cz)

  redis:
    host: 114.132.201.144
    port: 6379
    lettuce:
      pool:
        max-active: 300
    password: ENC(A2AdF7PLnAaQ14qVqCTuQw==)
