spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.201.144:3306/vpn?useUnicode=true&characterEncoding=utf-8
    username: root
    password: KangoShyVpn500